# =======================================
# Modern Essentials Plugin Configuration
# =======================================

# =========================
# Server List Options
# =========================
server-list:
  # Enables server list module
  enabled: true

  # MOTDs displayed in the server list
  motd:
    - |
      <gradient:#0956c6:#2a99fa><bold>Welcome to the Server</bold></gradient>
      <#2fa2ff>Have fun and enjoy your stay
    - |
      <gradient:#d83a06:#ffb047><bold>Multiple MOTDs are available</bold></gradient>
      <#ffbd50>One is chosen randomly on each refresh

  # Maximum number of players shown in the server list
  max-players: -1

  # Fake the number of online players displayed
  fake-players: -1

  # Hide the online player count completely
  hide-player-count: false

  # Disable hover text showing online players when hovering the player count
  disable-player-list-hover: false

# =========================
# Tab List Options
# =========================
tab-list:
  # Enables tab list module
  enabled: true

  # Format of each player's entry in the tab list
  format: "<player> <red><health>❤"

  # Header and footer displayed in the tab list
  header:
    - ''
    - '<gray>Ping: <#60afff><ping> <gray>| IP: <#60afff>example.com <gray>| Online: <#60afff><online>/<online_max>'
    - ''
  footer:
    - ''
    - "<gray>Server Time: <#60afff><time:'EEE, LLL dd yyyy'> <gray>| <#60afff><time:'HH:mm:ss'>"
    - ''

  # How often the tab is refreshed in ticks
  refresh-interval: 20

# =========================
# Chat Formatting
# =========================
chat:
  # Enables chat module
  enabled: true

  # Format of chat messages
  format: "<player_head> <gray><player> <dark_gray>> <white><message>"

# =========================
# Join & Quit Messages
# =========================
join-quit:
  # Enables join quit module
  enabled: true

  # Custom join message
  join-message: "<green>+ <player> <gray>Connected"

  # Custom quit message
  quit-message: "<red>- <player> <gray>Disconnected"

# =========================
# Death Message Formatting
# =========================
death-message:
  # Enables death message module
  enabled: true

  # Format of death messages
  format: "<gray>☠ <white><message>"

# =========================
# Command Whitelist
# =========================
command-whitelist:
  # Enables command whitelist module
  enabled: false

  # List of whitelisted commands
  whitelist:
    - help
    - msg

# =========================
# Commands
# =========================
commands:
  # List of essentials commands to disable
  # Only applied on server reload or restart
  disabled:
  #  - inventorysee
  #  - enderchest
