name: modern-essentials
main: com.uravgcode.modernessentials.ModernEssentials
bootstrapper: com.uravgcode.modernessentials.ModernEssentialsBootstrap
folia-supported: true
version: ${version}
api-version: '1.21'

description: a modern essentials plugin
website: 'https://uravgcode.com'
authors: [ UrAvgCode ]

dependencies:
  server:
    MiniPlaceholders:
      load: BEFORE
      required: false
      join-classpath: true
